"vsetvli t0, %[arr_size], e16\n\t"
"addi %[others_cnt],%[others_cnt],1\n\t"
"for:\n\t"
"addi %[lw_cnt],%[lw_cnt],2\n\t"
"vle16.v v0,(%[h])\n\t"
"vle16.v v1,(%[x])\n\t"
"addi %[mul_cnt],%[mul_cnt],1\n\t"
"vmul.vv v0, v0, v1\n\t"
"addi %[add_cnt],%[add_cnt],1\n\t"
"vadd.vx v0, v0, %[id]\n"
"addi %[sw_cnt],%[sw_cnt],1\n\t"
"vse16.v v0, (%[y])\n"
"addi %[add_cnt],%[add_cnt],4\n\t"
"addi %[h],%[h],16\n\t"
"addi %[x],%[x],16\n\t"
"addi %[y],%[y],16\n\t"
"addi %[arr_size],%[arr_size],-8\n\t"
"addi %[others_cnt],%[others_cnt],1\n\t"
"blt zero,%[arr_size],for\n\t"
